=== mlj365/sino/out/smbi/WEB-INF/config/config.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT config (param*, freeVisit*, limitedVisit*, configLoader*, dataFilter*, virtualPaths*)+> 

<!ELEMENT param (#PCDATA)> 

<!ATTLIST param
    name CDATA #REQUIRED
    value CDATA #REQUIRED
    remark CDATA #IMPLIED
    client (T|F) #IMPLIED 
>


<!ELEMENT freeVisit (type*, resource*, call*, exclude*)+>

<!ELEMENT type (#PCDATA)>
<!ELEMENT resource (#PCDATA)>
<!ELEMENT call (#PCDATA)>
<!ELEMENT exclude (#PCDATA)>


<!ELEMENT limitedVisit (roleResource*)+>
<!ELEMENT roleResource (#PCDATA)>
<!ATTLIST roleResource
	role CDATA #REQUIRED
	resource CDATA #REQUIRED
>

<!ELEMENT virtualPaths (virtualPath*)+>
<!ELEMENT virtualPath (#PCDATA)>
<!ATTLIST virtualPath
	path CDATA #REQUIRED
	target CDATA #IMPLIED
	classname CDATA #IMPLIED
>

<!ELEMENT configLoader (loader)*>

<!ELEMENT loader (#PCDATA)>
<!ATTLIST loader
	name CDATA #REQUIRED
	classname CDATA #REQUIRED
	active CDATA #REQUIRED
>

<!ELEMENT dataFilter (filter)*>
<!ELEMENT filter (#PCDATA)>
<!ATTLIST filter
	tablename CDATA #REQUIRED
	where CDATA #REQUIRED
>

=== mlj365/sino/WebRoot/WEB-INF/config/config.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE config PUBLIC "config" "config.dtd" >

<config>
	<!--系统参数-->
	<param name="EnvironmentName" value="Straumann系统" client="T" remark="测试环境、生产环境" />
	<param name="AuthorizeActive" value="T" remark="权限验证是否启用" />
	<param name="AppName" value="smbi" client="T" remark="应用名称" />
	<param name="DataBaseType" value="SQLServer" remark="Oracle,SQLServer,MySql" />
	<param name="TimeOutPage" client="T" value="page/system/login.html" remark="超时页面" />
	<param name="SendSMS" value="F" remark="是否发送短信，T，F" />
	<param name="SuperVCode" value="EDC4rfv" remark="超级验证码" />
	<param name="uploadFilePath" value="D:\upload" remark="附件上传路径" />
	<param name="fileRepository" value="@{path_webinfo}/repository" remark="" />
	<param name="applicationTemplateRoot" value="@{path_webinfo}/application/template/" remark="" />
	<param name="defaultExcel2007Template" value="@{fileRepository}/template/data.xlsx" remark="excel2007默认导出模板" />
	<param name="defaultExcel2003Template" value="@{fileRepository}/template/data.xls" remark="excel2003默认导出模板" />
	<param name="ModelPicPathRoot" value="@{path_application}/model" remark="modelPicPath" />
	<param name="URL_WebMan" value="http://192.168.5.63:3456/api/" remark="WebMan"/>
	<param name="adminCode" value="U108272" remark="admin人看的指标对应的人"/>
	<param name="DbFilePath" value="D:\sqlserverdb\" remark="文件目录"/>

	<!-- 2.不受权限控制的资源 -->
	<freeVisit>
		<!-- 2.1不受权限控制的资源类型 -->
		<type>.js</type>
		<type>.json</type>
		<type>.css</type>
		<type>.jpg</type>
		<type>.png</type>
		<type>.gif</type>
		<type>.bmp</type>
		<type>.jpeg</type>
		<type>.zip</type>
		<type>.map</type>
		<type>.svg</type>
		
		<!-- 2.2不受权限控制的页面 -->
		<resource>*/timeout.html</resource>
		<resource>*/login.html</resource>
		<resource>*/neg_login.html</resource>
		<resource>*/index.html</resource>
		<resource>*/print.html</resource>
		
		<!-- 2.3不受权限控制的函数调用 -->
		<call>user/login</call>
		<call>user/logout</call>
		<call>user/getvcade</call>
		<call>user/dataexists</call>
		

	</freeVisit>

	<!-- 3.角色页面关系 -->
	<limitedVisit>

	</limitedVisit>	

	<!-- 4.虚路径配置 -->
	<virtualPaths>
		<virtualPath path="/" target="page/system/login.html" />
		<virtualPath path="root" target="/smbi/" />
		<virtualPath path="data" classname="foundation.persist.DataObject" />
		<virtualPath path="user" classname="foundation.user.User" />
		<virtualPath path="dictionary" classname="foundation.dictionary.DictionaryService" />
		<virtualPath path="file" classname="foundation.file.FileCenter" />
		<virtualPath path="console" classname="report.Console" />
		<virtualPath path="chart" classname="report.Chart" />
		<virtualPath path="message" classname="phonecode.SendVcode" />
		<virtualPath path="distributition" classname="report.Distributition" />
		<virtualPath path="bi" classname="bi.Console"/>
	</virtualPaths>
	
	<!-- 6.配置信息加载器列表 -->
	<configLoader>
		<loader name="datasource" classname="foundation.persist.DatasuorceLoader" active="T"/>
		<loader name="namedSQL" classname="foundation.persist.sql.NamedSQLLoader" active="T"/>
		<loader name="dictionary" classname="foundation.dictionary.DictionaryLoader" active="T"/>
		<loader name="schedule" classname="foundation.shedule.ScheduleJobLoader" active="T"/>
		<loader name="fileIO" classname="foundation.file.mapping.FileIOLoader" active="F"/>
		<loader name="agg" classname="bi.define.AggTableContainer" active="T"/>
	</configLoader>
	
	<!-- 7.数据过滤权限 -->
	<dataFilter>
	</dataFilter>
</config>
